language: php
php:
  - '7.1'
services:
  - docker
before_script:
  - cp .env_dist .env
  - docker-compose up -d --build
  - docker-compose exec --user=root application composer install
  - docker-compose exec --user=root application bin/console doctrine:schema:update --force
  - docker-compose exec --user=root application bin/console doctrine:fixtures:load -n
script:
  - docker exec --user=root application ./vendor/bin/simple-phpunit
matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm
  fast_finish: true
notifications:
    on_success: never
    on_failure: always
after_success:
#  - travis_retry docker exec --user=root application php vendor/bin/coveralls
  - docker exec --user=root application ./vendor/bin/simple-phpunit --coverage-clover build/logs/clover.xml