# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
  api.plan_rate_calculation:
    class: ApiBundle\Service\Strategy\PlanRateCalculation
  api.rate_calculation:
    class: ApiBundle\Service\Strategy\RateCalculation
  api.call_normalizer:
    class: ApiBundle\Service\Normalize\CallNormalizer

